<LobbyScreen>:
    game_list: game_list

    BoxLayout:
        orientation: 'vertical'

        ScrollView:
            BoxLayout:
                id: game_list
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height

        BoxLayout:
            size_hint_y: None
            height: self.minimum_height

            Label:
                text: 'Name:'
                padding: dp(20), dp(20)
                size_hint_x: None
                width: self.texture_size[0]

            TextInput:
                id: game_name
                size_hint_y: None
                height: self.minimum_height

            Button:
                text: 'Create race'
                padding: dp(20), dp(20)
                size_hint_x: None
                width: self.texture_size[0]
                on_press: root.do_create_race(game_name.text)


<Game@BoxLayout>:
    name: ''
    address: []
    lobby: None
    size_hint_y: None
    height: dp(30)

    Label:
        text: root.name

    Button:
        text: 'Join'
        padding: dp(20), dp(20)
        size_hint_x: None
        width: self.texture_size[0]
        on_press: root.lobby.do_join_race(root.address)
